### ISSUE TITLE
Command to get server info

### ISSUE THREAD

**Issue by edyrkaj** [silverbucket/redis-connection-pool#73]
On the previous version was a method called: `serverInfo()`

- Is there something or a way to get the same results?

I am trying to use send_command('info') but can't not get any results from the Promise.
_source:_
https://redis.io/commands/info/

**Comment by silverbucket** [comment]
Hi @edyrkaj - you should be able to do this with the `sendCommand` method (which has been refactored recently). https://github.com/silverbucket/node-redis-connection-pool/blob/master/API.md#RedisConnectionPool+sendCommand

```javascript
const serverInfo = await pool.sendCommand('INFO');
```
